// Mock Three.js for testing
module.exports = {
  Matrix4: jest.fn(() => ({
    identity: jest.fn(),
    multiply: jest.fn(),
    multiplyMatrices: jest.fn(),
    set: jest.fn(),
    makeRotationX: jest.fn(),
    makeRotationY: jest.fn(),
    makeRotationZ: jest.fn(),
    makeScale: jest.fn(),
    makeTranslation: jest.fn(),
    decompose: jest.fn(),
    compose: jest.fn(),
    invert: jest.fn(),
    determinant: jest.fn(),
    getInverse: jest.fn(),
    transpose: jest.fn(),
    setPosition: jest.fn(),
    scale: jest.fn(),
    getMaxScaleOnAxis: jest.fn(),
    makeOrthographic: jest.fn(),
    equals: jest.fn(),
    fromArray: jest.fn(),
    toArray: jest.fn(),
    clone: jest.fn(),
    copy: jest.fn(),
  })),
  Scene: jest.fn(() => ({
    add: jest.fn(),
    remove: jest.fn(),
    traverse: jest.fn(),
    children: [],
  })),
  WebGLRenderer: jest.fn(() => ({
    setSize: jest.fn(),
    setPixelRatio: jest.fn(),
    render: jest.fn(),
    dispose: jest.fn(),
    domElement: document.createElement('canvas'),
  })),
  PerspectiveCamera: jest.fn(() => ({
    position: { set: jest.fn() },
    lookAt: jest.fn(),
  })),
  DirectionalLight: jest.fn(() => ({
    position: { 
      set: jest.fn().mockReturnValue({
        normalize: jest.fn().mockReturnThis()
      })
    },
  })),
  AmbientLight: jest.fn(),
  Vector3: jest.fn(() => ({ 
    x: 0, 
    y: 0, 
    z: 0,
    set: jest.fn().mockReturnThis(),
    copy: jest.fn().mockReturnThis(),
    add: jest.fn().mockReturnThis(),
    sub: jest.fn().mockReturnThis(),
    normalize: jest.fn().mockReturnThis(),
  })),
  Clock: jest.fn(() => ({
    getDelta: jest.fn(() => 0.016),
    getElapsedTime: jest.fn(() => 1),
    start: jest.fn(),
    stop: jest.fn(),
  })),
  AnimationMixer: jest.fn(() => ({
    update: jest.fn(),
    clipAction: jest.fn(() => ({
      play: jest.fn(),
      stop: jest.fn(),
      reset: jest.fn(),
      setLoop: jest.fn(),
      setEffectiveWeight: jest.fn(),
      paused: false,
      timeScale: 1,
    })),
    stopAllAction: jest.fn(),
    getRoot: jest.fn(() => ({ animations: [] })),
  })),
  Object3D: jest.fn(() => ({ 
    position: { x: 0, y: 0, z: 0, set: jest.fn() },
    quaternion: { x: 0, y: 0, z: 0, w: 1 },
    scale: { x: 1, y: 1, z: 1 },
  })),
  Mesh: jest.fn(),
  Group: jest.fn(),
  Quaternion: jest.fn(() => ({ 
    x: 0, 
    y: 0, 
    z: 0, 
    w: 1,
    set: jest.fn().mockReturnThis(),
    copy: jest.fn().mockReturnThis(),
  })),
  Euler: jest.fn(() => ({ 
    x: 0, 
    y: 0, 
    z: 0,
    set: jest.fn().mockReturnThis(),
  })),
  MathUtils: {
    DEG2RAD: Math.PI / 180,
  },
  LoopOnce: 'LoopOnce',
  LoopRepeat: 'LoopRepeat',
  sRGBEncoding: 'sRGBEncoding',
};